name: Project CI/CD

on:
  push:
    branches:
      - aslan
  pull_request: 
  workflow_dispatch: 

permissions: 
    contents: read

jobs:
  compile:
    name: Compile prject
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Compile project
        run: |
          mkdir -p out
          find src -name "*.java" -print0 | xargs -0 javac -d out

      - name: Run simple check
        run: java -cp out kbtu.university.MainPartBCheck