name: Project CI/CD

on:
  push:
    branches:
      - aslan
  pull_request: 
  workflow_dispatch: 

permissions: 
    contents: read

jobs:
  compile:
    name: Compile project
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v5

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Compile project
        run: |
          mkdir -p out
          find src -name "*.java" > sources.txt
          javac -encoding UTF-8 -d out @sources.txt

      - name: Run simple check
        run: java -cp out kbtu.university.MainPartBCheck

      - name: Show java version
        run: java -version

      - name: Upload compiled classes artifact
        uses: actions/upload-artifact@v4
        with:
            name: compiled-classes
            path: out